default:
  image: jla/base

variables:
  GIT_DEPTH: 200
  GIT_FETCH_EXTRA_FLAGS: --prune --tags
  GIT_SUBMODULE_STRATEGY: recursive


.bootstrap-and-configure:
  variables:
    CX: "CXX-is-unspecified"
    CXXFLAGS: "-Werror"
    BOOST_VERSION: "BOOST_VERSION-is-unspecified"
    CMAKE_ARG: ""
  before_script:
  - ./bootstrap.sh
  - mkdir build
  - cd build
  - echo "CXX=$CXX\nCXXFLAGS=$CXXFLAGS\nBOOST_VERSION=$BOOST_VERSION"
  - cmake ../ -DBUILD_BIN_BENCHMARK=on -DBUILD_BIN_ALL_ALG=on -DBUILD_EXAMPLES=on -DBUILD_TESTING=on -DBUILD_TESTING_SANITIZERS=off -DCMAKE_PREFIX_PATH=/opt/boost/$BOOST_VERSION $CMAKE_ARG


q:build:
  extends: .bootstrap-and-configure
  parallel:
    matrix:
    - CXX:
      - "g++-11"
      - "g++-12"
      - "g++-13"
      - "g++-14"
      - "clang++-14"
      - "clang++-15"
      - "clang++-16"
      - "clang++-17"
      - "clang++-18"
      - "clang++-19"
      - "clang++-20"
      BOOST_VERSION:
      - "1_77_0"
      - "1_78_0"
      - "1_79_0"
      - "1_80_0"
      - "1_81_0"
      - "1_82_0"
      - "1_83_0"
      - "1_84_0"
      - "1_85_0"
      - "1_86_0"
      - "1_87_0"
      - "1_88_0"
  script:
  - make
  - make install
  - make tests
  - ctest --output-on-failure
